name: onestep_imagepicker
description: onestep_imagepicker.
version: 1.0.0+1
homepage : https://github.com/honghoker/Onestep_imagePicker

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^6.0.1
  meta: ^1.7.0
  photo_manager: ^2.0.0-dev.11
  provider: ^6.0.1
  video_player: ^2.2.14
  fluttertoast: ^8.0.9


  