name: onestep_imagepicker
description: onestep_imagepicker.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  extended_image: ^6.0.1
  meta: ^1.7.0
  photo_manager: ^2.0.0-dev.11
  provider: ^6.0.1
  video_player: ^2.2.14
  fluttertoast: ^8.0.9